version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: sh -c "ollama serve & sleep 10 && ollama pull llama2 && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - PORT=3000
      - LOG_LEVEL=debug
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data:
