apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api
  namespace: llm-system
  labels:
    app: llm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: llm-api
        image: ${DOCKER_REGISTRY}/llm-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: OLLAMA_URL
          value: "http://ollama:11434"
        - name: OLLAMA_MODEL
          value: "llama3:32b"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llm-api
  namespace: llm-system
spec:
  selector:
    app: llm-api
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: ClusterIP 